# Generated by Django 6.0.1 on 2026-02-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otp_otp_alter_otp_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
