# Generated by Django 6.0.1 on 2026-02-17 13:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=100)),
                ('item_subcategory', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=150)),
                ('item_oldprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_newprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_description', tinymce.models.HTMLField()),
                ('item_instock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gifting.product')),
            ],
        ),
    ]
