# Generated by Django 6.0.1 on 2026-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('items_json', models.CharField(default='', max_length=2000)),
                ('price_json', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.IntegerField(default='')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
