# Generated by Django 6.0.1 on 2026-02-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0005_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
